# RabbitMQ URL, defaults to ENV['AMQP_URL']
amqp_url: <%= ENV['AMQP_URL'] %>

# Execution storage scenario: cloud | nfs | local 
storage: <%= ENV['STORAGE'] || 'cloud' %>

# Number of execution threads (defaults to: ENV['THREADS'], `nprocs` if available or 1)
threads: <%= Executor::cpu_count %>

# Cloud storage settings, the following hash is passed directyl to Fog::Storage, see http://fog.io/storage/ for further reference
# Defaults to AWS S3 with credentials passed in ENV
cloud_storage:
  provider: AWS
  aws_access_key_id:        <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key:    <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

plgdata:
  proxy: <%= File.read(ENV['GRID_PROXY']).inspect %>